# Generated by Django 4.1 on 2022-10-27 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Imagen', models.ImageField(default='pan.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=120)),
                ('Usuario', models.CharField(max_length=120)),
                ('Ciudad', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.CharField(max_length=150)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InOut_app.producto')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
